const $=(s,p=document)=>p.querySelector(s); const $$=(s,p=document)=>[...p.querySelectorAll(s)];
let token=localStorage.getItem('jd_admin_token')||''; let store=null;
const titles={dashboard:'Visão geral',bookings:'Agendamentos',hours:'Horários',media:'Fotos do site'};
async function api(url,opts={}){const h={'Content-Type':'application/json',...(opts.headers||{})};if(token)h.Authorization=`Bearer ${token}`;const r=await fetch(url,{...opts,headers:h});const data=await r.json().catch(()=>({}));if(r.status===401&&url!='/api/login'){logout(false);throw new Error('Sessão expirada.');}if(!r.ok)throw new Error(data.message||'Erro ao processar.');return data;}
function showApp(){ $('#loginScreen').hidden=true; $('#adminApp').hidden=false; loadAdmin(); }
function showLogin(){ $('#loginScreen').hidden=false; $('#adminApp').hidden=true; }
async function loadAdmin(){try{store=await api('/api/admin');renderAll();}catch(e){showLogin();}}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const st=$('#loginStatus');st.textContent='Entrando…';try{const d=await api('/api/login',{method:'POST',body:JSON.stringify({username:$('#loginUser').value.trim(),password:$('#loginPass').value})});token=d.token;localStorage.setItem('jd_admin_token',token);st.textContent='';showApp();}catch(err){st.textContent=err.message;}});
function logout(call=true){if(call&&token)api('/api/logout',{method:'POST'}).catch(()=>{});token='';localStorage.removeItem('jd_admin_token');showLogin();} $('#logoutBtn').addEventListener('click',()=>logout());
function go(tab){$$('.tab').forEach(x=>x.classList.remove('active'));$$('.nav-item').forEach(x=>x.classList.remove('active'));$(`#tab-${tab}`).classList.add('active');$(`.nav-item[data-tab="${tab}"]`)?.classList.add('active');$('#pageTitle').textContent=titles[tab];$('.sidebar').classList.remove('open');}
$$('.nav-item').forEach(b=>b.onclick=()=>go(b.dataset.tab));$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#mobileMenu').onclick=()=>$('.sidebar').classList.toggle('open');
function formatDate(s){if(!s)return'';const [y,m,d]=s.split('-');return `${d}/${m}/${y}`;}function formatCreated(s){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(s))}catch{return s}}
function digits(v){return String(v||'').replace(/\D/g,'')}function waFor(b){const msg=`Olá, ${b.name}! 💗 Aqui é do Studio JD Nails. Recebemos seu pedido para ${b.service} em ${formatDate(b.date)} às ${b.time}. Gostaria de confirmar seu horário.`;return `https://wa.me/55${digits(b.phone).replace(/^55/,'')}?text=${encodeURIComponent(msg)}`;}
function bookingHtml(b){return `<article class="booking-card"><div class="booking-name"><strong>${esc(b.name)}</strong><small>${esc(b.service)} • ${esc(b.phone)}</small><small>${esc(b.notes||'Sem observações')}</small></div><div class="booking-date"><strong>${formatDate(b.date)} às ${esc(b.time)}</strong><small>Recebido em ${formatCreated(b.createdAt)}</small><span class="status ${b.status}">${b.status}</span></div><div class="booking-actions"><a class="wa-btn" href="${waFor(b)}" target="_blank">WhatsApp ✓</a><button class="mini-btn" onclick="setStatus('${b.id}','confirmado')">Confirmar</button><button class="mini-btn" onclick="setStatus('${b.id}','concluido')">Concluído</button><button class="mini-btn" onclick="setStatus('${b.id}','cancelado')">Cancelar</button><button class="mini-btn danger" onclick="deleteBooking('${b.id}')">Excluir</button></div></article>`;}
function renderBookings(){const f=$('#bookingFilter').value;const list=f==='all'?store.bookings:store.bookings.filter(x=>x.status===f);$('#bookingsList').innerHTML=list.length?list.map(bookingHtml).join(''):'<div class="empty">Nenhum agendamento nesta categoria.</div>';$('#recentBookings').innerHTML=store.bookings.length?store.bookings.slice(0,5).map(bookingHtml).join(''):'<div class="empty">Ainda não há pedidos.</div>';}
window.setStatus=async(id,status)=>{await api('/api/bookings/status',{method:'PUT',body:JSON.stringify({id,status})});store.bookings.find(x=>x.id===id).status=status;renderAll();};window.deleteBooking=async id=>{if(!confirm('Excluir este agendamento?'))return;await api('/api/bookings/delete',{method:'POST',body:JSON.stringify({id})});store.bookings=store.bookings.filter(x=>x.id!==id);renderAll();};$('#bookingFilter').onchange=renderBookings;
function renderStats(){const all=store.bookings.length;$('#statAll').textContent=all;$('#statPending').textContent=store.bookings.filter(x=>x.status==='pendente').length;$('#statConfirmed').textContent=store.bookings.filter(x=>x.status==='confirmado').length;$('#statPhotos').textContent=store.media.portfolio.length;}
function renderHours(){const box=$('#hoursEditor');box.innerHTML=Object.entries(store.settings.hours).map(([k,h])=>`<div class="hour-row" data-day="${k}"><strong>${h.label}</strong><label><input class="closed" type="checkbox" ${h.closed?'checked':''}> Fechado</label><input class="open" type="time" value="${h.open||'09:00'}" ${h.closed?'disabled':''}><input class="close" type="time" value="${h.close||'20:00'}" ${h.closed?'disabled':''}></div>`).join('');$$('.hour-row .closed').forEach(c=>c.onchange=()=>{const r=c.closest('.hour-row');$$('input[type=time]',r).forEach(i=>i.disabled=c.checked)});renderBlocked();}
$('#saveHours').onclick=async()=>{const hours={};$$('.hour-row').forEach(r=>{const k=r.dataset.day;hours[k]={label:store.settings.hours[k].label,closed:$('.closed',r).checked,open:$('.open',r).value,close:$('.close',r).value};});await api('/api/settings',{method:'PUT',body:JSON.stringify({hours})});store.settings.hours=hours;alert('Horários salvos com sucesso!');};
function renderBlocked(){$('#blockedDates').innerHTML=(store.settings.blockedDates||[]).length?store.settings.blockedDates.map(d=>`<span class="chip">${formatDate(d)} <button onclick="removeBlocked('${d}')">×</button></span>`).join(''):'<small class="empty">Nenhuma data extra bloqueada.</small>';}
$('#addBlocked').onclick=async()=>{const d=$('#blockedDate').value;if(!d)return alert('Escolha uma data.');const set=[...new Set([...(store.settings.blockedDates||[]),d])].sort();await api('/api/settings',{method:'PUT',body:JSON.stringify({blockedDates:set})});store.settings.blockedDates=set;$('#blockedDate').value='';renderBlocked();};window.removeBlocked=async d=>{const set=(store.settings.blockedDates||[]).filter(x=>x!==d);await api('/api/settings',{method:'PUT',body:JSON.stringify({blockedDates:set})});store.settings.blockedDates=set;renderBlocked();};
function renderMedia(){const arr=[];if(store.media.hero)arr.push({area:'hero',src:store.media.hero,title:'Foto principal'});if(store.media.about)arr.push({area:'about',src:store.media.about,title:'Seção Sobre'});store.media.portfolio.forEach(x=>arr.push({area:'portfolio',...x}));$('#mediaGrid').innerHTML=arr.length?arr.map(x=>`<article class="media-card"><img src="${x.src}" alt=""><span class="label">${esc(x.title||x.area)}</span><button title="Remover" onclick="removeMedia('${x.area}','${x.id||''}')">×</button></article>`).join(''):'<div class="empty">Nenhuma foto adicionada pelo painel.</div>';}
$('#mediaFile').onchange=e=>$('#fileName').textContent=e.target.files[0]?.name||'Nenhum arquivo escolhido';
function imageToDataUrl(file){return new Promise((resolve,reject)=>{const rd=new FileReader();rd.onerror=reject;rd.onload=()=>{const img=new Image();img.onload=()=>{const max=1600;const scale=Math.min(1,max/Math.max(img.width,img.height));const c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.84));};img.onerror=reject;img.src=rd.result;};rd.readAsDataURL(file);});}
$('#mediaForm').onsubmit=async e=>{e.preventDefault();const st=$('#mediaStatus');const file=$('#mediaFile').files[0];if(!file)return;st.textContent='Processando imagem…';try{const dataUrl=await imageToDataUrl(file);st.textContent='Enviando…';const d=await api('/api/media',{method:'POST',body:JSON.stringify({area:$('#mediaArea').value,title:$('#mediaTitle').value.trim(),category:$('#mediaCategory').value.trim(),dataUrl})});store.media=d.media;e.target.reset();$('#fileName').textContent='Nenhum arquivo escolhido';st.textContent='Imagem publicada com sucesso!';renderAll();}catch(err){st.textContent=err.message;}};
window.removeMedia=async(area,id)=>{if(!confirm('Remover esta imagem do site?'))return;const d=await api('/api/media/delete',{method:'POST',body:JSON.stringify({area,id})});store.media=d.media;renderAll();};
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function renderAll(){renderStats();renderBookings();renderHours();renderMedia();}
if(token)showApp();else showLogin();
